
export const SETTINGS_LOADING = 'SETTINGS_LOADING';
export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS';
export const SETTINGS_DONE = 'SETTINGS_DONE';
export const SETTINGS_ERROR = 'SETTINGS_ERROR';

export const SETTINGS_LOAD_USER_INFO = 'SETTINGS_LOAD_USER_INFO';
export const SETTINGS_UPDATE_LOCATION_SUCCESS = 'SETTINGS_UPDATE_LOCATION_SUCCESS';
export const SETTINGS_UPDATE_SERVICE_AREA_SUCCESS = 'SETTINGS_UPDATE_SERVICE_AREA_SUCCESS';
export const SETTINGS_UPDATE_SERVICE_PROVIDE_SUCCESS = 'SETTINGS_UPDATE_SERVICE_PROVIDE_SUCCESS';
export const SETTINGS_UPDATE_PROVIDER_MODE_SUCCESS = 'SETTINGS_UPDATE_PROVIDER_MODE_SUCCESS';