export const FAVOURITES_LOADING = 'FAVOURITES_LOADING';
export const FAVOURITES_SUCCESS = 'FAVOURITES_SUCCESS';
export const FAVOURITES_ERROR = 'FAVOURITES_ERROR';
export const FAVOURITES_ADDED_SUCCESS = 'FAVOURITES_ADDED_SUCCESS';
export const FAVOURITES_LOADED_SUCCESS = 'FAVOURITES_LOADED_SUCCESS';
export const FAVOURITES_REMOVED_SUCCESS = 'FAVOURITES_REMOVED_SUCCESS';