export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPLOAD_LOADING = 'UPLOAD_LOADING';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';
export const UPLOAD_AVATAR_DONE = 'UPLOAD_AVATAR_DONE';

