export const SIDEBAR_RESTORING = 'SIDEBAR_RESTORING';
export const SIDEBAR_DONE = 'SIDEBAR_DONE';
export const SIDEBAR_SUCCESS = 'SIDEBAR_SUCCESS';
export const SIDEBAR_ERROR = 'SIDEBAR_ERROR';
export const SIDEBAR_NEED_TO_RELOAD = 'SIDEBAR_NEED_TO_RELOAD';
// export const SIDEBAR_SIGNOUT = 'SIDEBAR_SIGNOUT'

