export const MESSAGE_LOADING = 'MESSAGE_LOADING'
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS'
export const MESSAGE_ERROR = 'MESSAGE_ERROR'
export const MESSAGE_UPDATE = 'MESSAGE_UPDATE'
export const MESSAGES_LOAD_SUCCESS = 'MESSAGES_LOAD_SUCCESS'
export const MESSAGES_LOAD_ERROR = 'MESSAGES_LOAD_ERROR'

export const MESSAGES_LOAD_CONVERSATIONS = 'MESSAGES_LOAD_CONVERSATIONS'