export const SERVICES_LOADING = 'SERVICES_LOADING';
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SERVICES_ERROR = 'SERVICES_ERROR';
export const SERVICES_LOADED_SUCCESS = 'SERVICES_LOADED_SUCCESS';
export const SERVICES_PROVIDER_LOADED_SUCCESS = 'SERVICES_PROVIDER_LOADED_SUCCESS';
