
export const REQUEST_SERVICE_LOADING = 'REQUEST_SERVICE_LOADING';
export const REQUEST_SERVICE_SUCCESS = 'REQUEST_SERVICE_SUCCESS';
export const REQUEST_SERVICE_DONE = 'REQUEST_SERVICE_DONE';
export const REQUEST_SERVICE_ERROR = 'REQUEST_SERVICE_ERROR';

export const REQUEST_SERVICE_LIST_LOADED_SUCCESS = 'REQUEST_SERVICE_LIST_LOADED_SUCCESS';
export const REQUEST_SERVICE_REVIEWS_LOADED_SUCCESS = 'REQUEST_SERVICE_REVIEWS_LOADED_SUCCESS';
