export const CHAT_MESSAGE_LOADING = 'CHAT_MESSAGE_LOADING'
export const CHAT_MESSAGE_SUCCESS = 'CHAT_MESSAGE_SUCCESS'
export const CHAT_MESSAGE_ERROR = 'CHAT_MESSAGE_ERROR'
export const CHAT_MESSAGE_UPDATE = 'CHAT_MESSAGE_UPDATE'
export const CHAT_LOAD_MESSAGES_SUCCESS = 'CHAT_LOAD_MESSAGES_SUCCESS'
export const CHAT_LOAD_MESSAGES_ERROR = 'CHAT_LOAD_MESSAGES_ERROR'


export const MESSAGE_LOADING = 'MESSAGE_LOADING'
export const MESSAGE_ERROR = 'MESSAGE_ERROR'
export const MESSAGE_LOADED_SUCCESS = 'MESSAGE_LOADED_SUCCESS'
export const MESSAGE_LOADED_SUCCESS_AFFIRMATION = 'MESSAGE_LOADED_SUCCESS_AFFIRMATION'
export const MESSAGE_LOADED_SNAPSHOT_SUCCESS = 'MESSAGE_LOADED_SNAPSHOT_SUCCESS'
export const MESSAGE_CONVERSATION_LIST_LOAD_SUCCESS = 'MESSAGE_CONVERSATION_LIST_LOAD_SUCCESS'
export const MESSAGE_SENT_SUCCESS = 'MESSAGE_SENT_SUCCESS'

