export const SESSION_RESTORING = 'SESSION_RESTORING';
export const SESSION_DONE = 'SESSION_DONE';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_ERROR = 'SESSION_ERROR';
export const SESSION_NEED_TO_RELOAD = 'SESSION_NEED_TO_RELOAD'
export const SESSION_SIGNOUT = 'SESSION_SIGNOUT'




