export const SERVICE_LOADING = 'SERVICE_LOADING';
export const SERVICE_SUCCESS = 'SERVICE_SUCCESS';
export const SERVICE_ERROR = 'SERVICE_ERROR';
export const SERVICE_LOAD_USER_SUCCESS = 'SERVICE_GET_USER_SUCCESS';
